"""
Unit Tests for Story 4-2: TG 消息推送

Tests cover message formatting and TelegramNotifier class.
All tests passing - feature implemented.

Generated by BMad TEA Agent - 2026-03-01
"""

from unittest.mock import AsyncMock, MagicMock

import pytest

from notifier import (
    TelegramNotifier,
    format_activity_message,
    format_eth,
    format_timestamp,
    format_usd,
    get_tx_url,
)

# ============================================================
# AC1: 实现 format_activity_message() 格式化活动消息
# ============================================================

class TestFormatActivityMessageExists:
    """测试 format_activity_message 函数存在"""

    def test_function_exists(self):
        """format_activity_message 函数应该存在且可调用"""
        assert callable(format_activity_message)

    def test_returns_string(self):
        """format_activity_message 应该返回字符串"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
        }
        result = format_activity_message(activity)
        assert isinstance(result, str)


# ============================================================
# AC2: 支持格式化 Swap/Deposit/Withdrawal 三种类型
# ============================================================

class TestFormatSwapMessage:
    """测试 Swap 消息格式化"""

    def test_format_swap_message_contains_type(self):
        """Swap 消息应该包含类型"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",
                "effectivePriceUsd": "3000.00"
            }
        }
        message = format_activity_message(activity)
        assert "SWAP" in message.upper()

    def test_format_swap_message_contains_side(self):
        """Swap 消息应该包含方向 (BUY/SELL)"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",
                "effectivePriceUsd": "3000.00"
            }
        }
        message = format_activity_message(activity)
        assert "BUY" in message

    def test_format_swap_message_contains_token(self):
        """Swap 消息应该包含代币符号"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",
                "effectivePriceUsd": "3000.00"
            }
        }
        message = format_activity_message(activity)
        assert "USDC" in message

    def test_format_swap_message_contains_eth_amount(self):
        """Swap 消息应该包含 ETH 数量 (从 Wei 转换)"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",  # 0.5 ETH
                "effectivePriceUsd": "3000.00"
            }
        }
        message = format_activity_message(activity)
        assert "0.500000" in message

    def test_format_swap_message_contains_price(self):
        """Swap 消息应该包含价格"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",
                "effectivePriceUsd": "3000.00"
            }
        }
        message = format_activity_message(activity)
        assert "3,000" in message or "3000" in message


class TestFormatDepositMessage:
    """测试 Deposit 消息格式化"""

    def test_format_deposit_message_contains_type(self):
        """Deposit 消息应该包含类型"""
        activity = {
            "id": "0xdef456",
            "type": "deposit",
            "timestamp": "2026-03-01T12:00:00Z",
            "deposit": {
                "amountWei": "1000000000000000000"
            }
        }
        message = format_activity_message(activity)
        assert "DEPOSIT" in message.upper()

    def test_format_deposit_message_contains_amount(self):
        """Deposit 消息应该包含金额 (从 Wei 转换)"""
        activity = {
            "id": "0xdef456",
            "type": "deposit",
            "timestamp": "2026-03-01T12:00:00Z",
            "deposit": {
                "amountWei": "1000000000000000000"  # 1 ETH
            }
        }
        message = format_activity_message(activity)
        assert "1.000000" in message


class TestFormatWithdrawalMessage:
    """测试 Withdrawal 消息格式化"""

    def test_format_withdrawal_message_contains_type(self):
        """Withdrawal 消息应该包含类型"""
        activity = {
            "id": "0x789xyz",
            "type": "withdrawal",
            "timestamp": "2026-03-01T12:00:00Z",
            "withdrawal": {
                "amountWei": "500000000000000000"
            }
        }
        message = format_activity_message(activity)
        assert "WITHDRAWAL" in message.upper()

    def test_format_withdrawal_message_contains_amount(self):
        """Withdrawal 消息应该包含金额 (从 Wei 转换)"""
        activity = {
            "id": "0x789xyz",
            "type": "withdrawal",
            "timestamp": "2026-03-01T12:00:00Z",
            "withdrawal": {
                "amountWei": "500000000000000000"  # 0.5 ETH
            }
        }
        message = format_activity_message(activity)
        assert "0.500000" in message


class TestFormatUnknownType:
    """测试未知类型处理"""

    def test_format_unknown_type_handled_gracefully(self):
        """未知类型应该优雅处理"""
        activity = {
            "id": "0xunknown",
            "type": "unknown_type",
            "timestamp": "2026-03-01T12:00:00Z",
        }
        message = format_activity_message(activity)
        assert isinstance(message, str)
        assert len(message) > 0


# ============================================================
# AC3: 推送到 ADMIN_USERS 或 ALLOWED_USERS
# ============================================================

class TestTelegramNotifierUserSelection:
    """测试用户选择逻辑"""

    def test_notifier_uses_explicit_users(self):
        """应该使用明确指定的用户列表"""
        mock_bot = MagicMock()
        explicit_users = [123456, 789012]

        notifier = TelegramNotifier(mock_bot, notify_users=explicit_users)

        assert notifier.notify_users == explicit_users

    def test_notifier_fallback_to_admin_users(self, monkeypatch):
        """没有指定用户时应该使用 ADMIN_USERS"""
        mock_bot = MagicMock()
        monkeypatch.setenv("ADMIN_USERS", "111222333")

        # 需要重新导入 config 和 notifier 以获取新的环境变量
        import importlib

        import config
        import notifier as notifier_mod

        importlib.reload(config)
        importlib.reload(notifier_mod)

        notifier = notifier_mod.TelegramNotifier(mock_bot)

        # ADMIN_USERS 应该被使用
        assert len(notifier.notify_users) > 0


class TestTelegramNotifierSendNotification:
    """测试发送通知逻辑"""

    @pytest.mark.asyncio
    async def test_send_notification_calls_bot(self):
        """send_notification 应该调用 bot.send_message"""
        mock_bot = MagicMock()
        mock_bot.send_message = AsyncMock()

        notifier = TelegramNotifier(mock_bot, notify_users=[123456])
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {"side": "BUY"}
        }

        await notifier.send_notification(activity)

        assert mock_bot.send_message.called

    @pytest.mark.asyncio
    async def test_send_notification_to_correct_user(self):
        """应该发送到正确的用户"""
        mock_bot = MagicMock()
        mock_bot.send_message = AsyncMock()

        notifier = TelegramNotifier(mock_bot, notify_users=[123456])
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {"side": "BUY"}
        }

        await notifier.send_notification(activity)

        call_args = mock_bot.send_message.call_args
        assert call_args.kwargs['chat_id'] == 123456

    @pytest.mark.asyncio
    async def test_send_notification_no_users_configured(self):
        """没有配置用户时应该跳过发送并记录日志"""
        mock_bot = MagicMock()
        mock_bot.send_message = AsyncMock()

        # Mock ADMIN_USERS and ALLOWED_USERS to be empty
        import notifier
        original_admin = notifier.ADMIN_USERS
        original_allowed = notifier.ALLOWED_USERS
        notifier.ADMIN_USERS = []
        notifier.ALLOWED_USERS = []

        try:
            notifier_instance = TelegramNotifier(mock_bot, notify_users=[])
            activity = {
                "id": "0xabc123",
                "type": "swap",
                "timestamp": "2026-03-01T12:00:00Z",
                "swap": {"side": "BUY"}
            }

            await notifier_instance.send_notification(activity)

            assert not mock_bot.send_message.called
        finally:
            notifier.ADMIN_USERS = original_admin
            notifier.ALLOWED_USERS = original_allowed


# ============================================================
# AC4: 消息包含: 操作类型、时间、金额/数量、交易链接
# ============================================================

class TestMessageContent:
    """测试消息内容完整性"""

    def test_message_contains_type(self):
        """消息应该包含操作类型"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {"side": "BUY"}
        }
        message = format_activity_message(activity)
        assert "Type" in message

    def test_message_contains_timestamp(self):
        """消息应该包含时间戳"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {"side": "BUY"}
        }
        message = format_activity_message(activity)
        assert "Time" in message
        assert "2026" in message

    def test_message_contains_tx_link(self):
        """消息应该包含交易链接"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {"side": "BUY"}
        }
        message = format_activity_message(activity)
        assert "etherscan" in message.lower()

    def test_message_no_link_when_no_id(self):
        """没有 ID 时不应该包含链接"""
        activity = {
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {"side": "BUY"}
        }
        message = format_activity_message(activity)
        # 消息应该仍然有效，只是没有链接
        assert isinstance(message, str)


class TestEtherscanUrlGeneration:
    """测试 Etherscan URL 生成"""

    def test_get_tx_url_mainnet(self):
        """主网应该生成正确的 Etherscan URL"""
        import notifier
        original_chain_id = notifier.CHAIN_ID
        notifier.CHAIN_ID = 1

        try:
            url = get_tx_url("0xabc123")
            assert "etherscan.io" in url
            assert "0xabc123" in url
        finally:
            notifier.CHAIN_ID = original_chain_id

    def test_get_tx_url_sepolia(self):
        """Sepolia 测试网应该生成正确的 URL"""
        import notifier
        original_chain_id = notifier.CHAIN_ID
        notifier.CHAIN_ID = 11155111

        try:
            url = get_tx_url("0xabc123")
            assert "sepolia.etherscan.io" in url
            assert "0xabc123" in url
        finally:
            notifier.CHAIN_ID = original_chain_id

    def test_get_tx_url_holesky(self):
        """Holesky 测试网应该生成正确的 URL"""
        import notifier
        original_chain_id = notifier.CHAIN_ID
        notifier.CHAIN_ID = 17000

        try:
            url = get_tx_url("0xabc123")
            assert "holesky.etherscan.io" in url
            assert "0xabc123" in url
        finally:
            notifier.CHAIN_ID = original_chain_id


class TestHelperFunctions:
    """测试辅助函数"""

    def test_format_eth_converts_wei(self):
        """format_eth 应该正确转换 Wei 到 ETH"""
        result = format_eth("1000000000000000000")  # 1 ETH
        assert result == "1.000000"

    def test_format_eth_handles_invalid(self):
        """format_eth 应该处理无效输入"""
        result = format_eth("invalid")
        assert result == "invalid"

    def test_format_usd_formats_value(self):
        """format_usd 应该正确格式化 USD"""
        result = format_usd("3000.00")
        assert "3,000" in result or "3000" in result

    def test_format_timestamp_converts_iso(self):
        """format_timestamp 应该正确格式化 ISO 时间戳"""
        result = format_timestamp("2026-03-01T12:00:00Z")
        assert "2026" in result
        assert "03" in result or "3" in result

    def test_format_timestamp_handles_invalid(self):
        """format_timestamp 应该处理无效输入"""
        result = format_timestamp("invalid")
        assert result == "invalid"

    def test_format_timestamp_handles_unix_timestamp(self):
        """format_timestamp 应该处理 Unix 时间戳（整数）"""
        # 1772368631 is around 2026-03-01 (user's actual data)
        result = format_timestamp(1772368631)
        # Should format as date string, not return raw number
        assert "-" in result  # Contains date separator
        assert ":" in result  # Contains time separator

    def test_format_timestamp_handles_unix_timestamp_string(self):
        """format_timestamp should handle Unix timestamp (string)"""
        result = format_timestamp("1772368631")
        # Should format as date string, not return raw number
        assert "-" in result  # Contains date separator
        assert ":" in result  # Contains time separator

    def test_format_timestamp_returns_utc(self):
        """format_timestamp should return UTC suffix"""
        result = format_timestamp("2026-03-01T12:00:00Z")
        assert "UTC" in result


class TestPriceFallback:
    """Test price field fallback logic"""

    def test_price_uses_effectivePriceUsd(self):
        """Should use effectivePriceUsd when available"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",
                "effectivePriceUsd": "3000.00",
                "priceUsd": "2000.00",
            }
        }
        message = format_activity_message(activity)
        assert "3,000" in message or "3000" in message

    def test_price_falls_back_to_priceUsd(self):
        """Should fall back to priceUsd when effectivePriceUsd is missing"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",
                "priceUsd": "2500.00",
            }
        }
        message = format_activity_message(activity)
        assert "2,500" in message or "2500" in message

    def test_price_falls_back_to_avgPriceUsd(self):
        """Should fall back to avgPriceUsd when other price fields are missing"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",
                "avgPriceUsd": "2800.00",
            }
        }
        message = format_activity_message(activity)
        assert "2,800" in message or "2800" in message

    def test_price_shows_zero_when_all_missing(self):
        """Should show $0.00 when all price fields are missing"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "USDC",
                "ethAmount": "500000000000000000",
            }
        }
        message = format_activity_message(activity)
        assert "$0.00" in message


class TestTokenQuantity:
    """Test token quantity display"""

    def test_shows_tokenAmount_when_available(self):
        """Should show token quantity when tokenAmount is available"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "HOLE",
                "ethAmount": "500000000000000000",
                "tokenAmount": "1000.5",
                "effectivePriceUsd": "0.00022",
            }
        }
        message = format_activity_message(activity)
        assert "Token Qty" in message
        # 1000.5 >= 1000, so formatted as 1.00K
        assert "1.00K" in message

    def test_shows_quantity_when_tokenAmount_missing(self):
        """Should show quantity field when tokenAmount is missing"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "HOLE",
                "ethAmount": "500000000000000000",
                "quantity": "500",
            }
        }
        message = format_activity_message(activity)
        assert "Token Qty" in message
        assert "500" in message

    def test_no_token_qty_when_both_missing(self):
        """Should not show Token Qty line when both fields are missing"""
        activity = {
            "id": "0xabc123",
            "type": "swap",
            "timestamp": "2026-03-01T12:00:00Z",
            "swap": {
                "side": "BUY",
                "tokenSymbol": "HOLE",
                "ethAmount": "500000000000000000",
            }
        }
        message = format_activity_message(activity)
        assert "Token Qty" not in message
